export const perfumes = [
  {
    name: "Azzaro Chrome Eau de Toilette",
    brand: "Azzaro",
    volume: [100],
    tone: "Cool & Bitter",
    scentFamily: "Citrus Aromatic",
    perfumer: ["Gérard Haury"],
    gender: "Men",
    perfumeType: "Eau de Toilette",
    season: "Spring, Summer",
    longevity: "Moderate",
    sillage: "Moderate",
    price: 70,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Azzaro Chrome Eau de Parfum",
    brand: "Azzaro",
    volume: [60, 100],
    tone: "Cool & Bitter",
    scentFamily: "Citrus Aromatic",
    perfumer: ["Gérard Haury"],
    gender: "Men",
    perfumeType: "Eau de Parfum",
    season: "Spring, Summer",
    longevity: "Long",
    sillage: "Moderate",
    price: 90,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Azzaro Visit",
    brand: "Azzaro",
    volume: [100],
    tone: "Warm & Spicy",
    scentFamily: "Woody Spicy",
    perfumer: [],
    gender: "Men",
    perfumeType: "Eau de Toilette",
    season: "Autumn, Winter",
    longevity: "Moderate",
    sillage: "Moderate",
    price: 75,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Azzaro Pour Homme",
    brand: "Azzaro",
    volume: [100],
    tone: "Warm & Spicy",
    scentFamily: "Woody Spicy",
    perfumer: ["Michel Hy"],
    gender: "Men",
    perfumeType: "Eau de Toilette",
    season: "Autumn, Winter",
    longevity: "Moderate",
    sillage: "Moderate",
    price: 65,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Azzaro Chrome United",
    brand: "Azzaro",
    volume: [100],
    tone: "Fresh & Aromatic",
    scentFamily: "Woody Aromatic",
    perfumer: ["Laurent Le Guernec"],
    gender: "Men",
    perfumeType: "Eau de Toilette",
    season: "Spring, Summer",
    longevity: "Moderate",
    sillage: "Moderate",
    price: 75,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Azzaro Most Wanted",
    brand: "Azzaro",
    volume: [100],
    tone: "Warm & Spicy",
    scentFamily: "Woody Spicy",
    perfumer: ["Jacques Huclier"],
    gender: "Men",
    perfumeType: "Eau de Toilette",
    season: "Autumn, Winter",
    longevity: "Long",
    sillage: "Moderate",
    price: 85,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Azzaro Chrome Legend",
    brand: "Azzaro",
    volume: [100],
    tone: "Fresh & Aromatic",
    scentFamily: "Woody Aromatic",
    perfumer: ["Laurent Le Guernec"],
    gender: "Men",
    perfumeType: "Eau de Toilette",
    season: "Spring, Summer",
    longevity: "Moderate",
    sillage: "Moderate",
    price: 80,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Azzaro Wanted By Night",
    brand: "Azzaro",
    volume: [100],
    tone: "Warm & Spicy",
    scentFamily: "Woody Spicy",
    perfumer: ["Lucas Sieuzac"],
    gender: "Men",
    perfumeType: "Eau de Parfum",
    season: "Autumn, Winter",
    longevity: "Long",
    sillage: "Strong",
    price: 95,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Azzaro Wanted EDT",
    brand: "Azzaro",
    volume: [50, 100],
    tone: "Warm & Spicy",
    scentFamily: "Woody Spicy",
    perfumer: ["Lucas Sieuzac"],
    gender: "Men",
    perfumeType: "Eau de Toilette",
    season: "Autumn, Winter",
    longevity: "Moderate",
    sillage: "Moderate",
    price: 85,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Azzaro Wanted EDP",
    brand: "Azzaro",
    volume: [50, 100],
    tone: "Warm & Spicy",
    scentFamily: "Woody Spicy",
    perfumer: ["Lucas Sieuzac"],
    gender: "Men",
    perfumeType: "Eau de Parfum",
    season: "Autumn, Winter",
    longevity: "Long",
    sillage: "Strong",
    price: 95,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Aigner Starlight",
    brand: "Aigner",
    volume: [100],
    tone: "Warm & Sweet",
    scentFamily: "Oriental Floral",
    perfumer: [],
    gender: "Women",
    perfumeType: "Eau de Parfum",
    season: "Autumn, Winter",
    longevity: "Moderate",
    sillage: "Moderate",
    price: 70,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Aigner White for Men",
    brand: "Aigner",
    volume: [100],
    tone: "Fresh & Aromatic",
    scentFamily: "Woody Aromatic",
    perfumer: [],
    gender: "Men",
    perfumeType: "Eau de Toilette",
    season: "Spring, Summer",
    longevity: "Moderate",
    sillage: "Moderate",
    price: 65,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Aigner Debut",
    brand: "Aigner",
    volume: [100],
    tone: "Fresh & Sweet",
    scentFamily: "Floral Fruity",
    perfumer: [],
    gender: "Women",
    perfumeType: "Eau de Parfum",
    season: "Spring, Summer",
    longevity: "Moderate",
    sillage: "Moderate",
    price: 70,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Antonio Banderas Blue Seduction for Men",
    brand: "Antonio Banderas",
    volume: [100],
    tone: "Fresh & Aquatic",
    scentFamily: "Aromatic Aquatic",
    perfumer: [],
    gender: "Men",
    perfumeType: "Eau de Toilette",
    season: "Spring, Summer",
    longevity: "Moderate",
    sillage: "Moderate",
    price: 50,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Antonio Banderas Blue Seduction for Men",
    brand: "Antonio Banderas",
    volume: [100],
    tone: "Fresh & Aquatic",
    scentFamily: "Aromatic Aquatic",
    perfumer: [],
    gender: "Men",
    perfumeType: "Eau de Toilette",
    season: "Spring, Summer",
    longevity: "Moderate",
    sillage: "Moderate",
    price: 50,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Antonio Banderas Blue Seduction for Women",
    brand: "Antonio Banderas",
    volume: [100],
    tone: "Fresh & Fruity",
    scentFamily: "Floral Fruity",
    perfumer: [],
    gender: "Women",
    perfumeType: "Eau de Toilette",
    season: "Spring, Summer",
    longevity: "Moderate",
    sillage: "Moderate",
    price: 50,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Aramis for Men",
    brand: "Aramis",
    volume: [100],
    tone: "Warm & Spicy",
    scentFamily: "Woody Spicy",
    perfumer: [],
    gender: "Men",
    perfumeType: "Eau de Toilette",
    season: "Autumn, Winter",
    longevity: "Long",
    sillage: "Strong",
    price: 90,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Club de Night Sillage",
    brand: "Armaf",
    volume: [105, 150, 200],
    tone: "Fresh & Spicy",
    scentFamily: "Woody Spicy",
    perfumer: [],
    gender: "Men",
    perfumeType: "Eau de Parfum",
    season: "Spring, Summer, Autumn",
    longevity: "Long",
    sillage: "Strong",
    price: 60,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Club de Night Blue Iconic",
    brand: "Armaf",
    volume: [105, 150, 200],
    tone: "Fresh & Citrusy",
    scentFamily: "Aromatic Aquatic",
    perfumer: [],
    gender: "Men",
    perfumeType: "Eau de Parfum",
    season: "Spring, Summer",
    longevity: "Long",
    sillage: "Strong",
    price: 60,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Club de Night Intense",
    brand: "Armaf",
    volume: [105, 150, 200],
    tone: "Warm & Spicy",
    scentFamily: "Woody Spicy",
    perfumer: [],
    gender: "Men",
    perfumeType: "Eau de Parfum",
    season: "Autumn, Winter",
    longevity: "Long",
    sillage: "Strong",
    price: 65,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Precieux",
    brand: "Armaf",
    volume: [100],
    tone: "Warm & Sweet",
    scentFamily: "Oriental Floral",
    perfumer: [],
    gender: "Women",
    perfumeType: "Eau de Parfum",
    season: "Autumn, Winter",
    longevity: "Moderate",
    sillage: "Moderate",
    price: 55,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Club de Night for Women",
    brand: "Armaf",
    volume: [100],
    tone: "Fresh & Fruity",
    scentFamily: "Floral Fruity",
    perfumer: [],
    gender: "Women",
    perfumeType: "Eau de Parfum",
    season: "Spring, Summer",
    longevity: "Moderate",
    sillage: "Moderate",
    price: 55,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Aqva Pour Homme",
    brand: "Bvlgari",
    volume: [100],
    tone: "Fresh & Aquatic",
    scentFamily: "Aromatic Aquatic",
    perfumer: [],
    gender: "Men",
    perfumeType: "Eau de Toilette",
    season: "Spring, Summer",
    longevity: "Moderate",
    sillage: "Moderate",
    price: 80,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Bvlgari Sahare",
    brand: "Bvlgari",
    volume: [100],
    tone: "Warm & Spicy",
    scentFamily: "Woody Spicy",
    perfumer: [],
    gender: "Men",
    perfumeType: "Eau de Toilette",
    season: "Autumn, Winter",
    longevity: "Long",
    sillage: "Moderate",
    price: 90,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Aramis Devin",
    brand: "Aramis",
    volume: [100],
    tone: "Fresh & Citrus",
    scentFamily: "Aromatic Citrus",
    perfumer: [],
    gender: "Men",
    perfumeType: "Eau de Toilette",
    season: "Spring, Summer",
    longevity: "Moderate",
    sillage: "Moderate",
    price: 85,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Bvlgari Man In Black",
    brand: "Bvlgari",
    volume: [100],
    tone: "Warm & Spicy",
    scentFamily: "Oriental Spicy",
    perfumer: [],
    gender: "Men",
    perfumeType: "Eau de Parfum",
    season: "Autumn, Winter",
    longevity: "Long",
    sillage: "Strong",
    price: 120,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Bvlgari Onekh",
    brand: "Bvlgari",
    volume: [100],
    tone: "Warm & Spicy",
    scentFamily: "Woody Spicy",
    perfumer: [],
    gender: "Men",
    perfumeType: "Eau de Parfum",
    season: "Autumn, Winter",
    longevity: "Long",
    sillage: "Strong",
    price: 110,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Bvlgari Sahare",
    brand: "Bvlgari",
    volume: [100],
    tone: "Warm & Spicy",
    scentFamily: "Woody Spicy",
    perfumer: [],
    gender: "Men",
    perfumeType: "Eau de Toilette",
    season: "Autumn, Winter",
    longevity: "Long",
    sillage: "Moderate",
    price: 90,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Bvlgari Gyan",
    brand: "Bvlgari",
    volume: [100],
    tone: "Fresh & Citrus",
    scentFamily: "Aromatic Citrus",
    perfumer: [],
    gender: "Men",
    perfumeType: "Eau de Toilette",
    season: "Spring, Summer",
    longevity: "Moderate",
    sillage: "Moderate",
    price: 95,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Bvlgari Tygar",
    brand: "Bvlgari",
    volume: [100],
    tone: "Warm & Spicy",
    scentFamily: "Woody Oriental",
    perfumer: [],
    gender: "Men",
    perfumeType: "Eau de Parfum",
    season: "Autumn, Winter",
    longevity: "Long",
    sillage: "Strong",
    price: 105,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Bvlgari Falkar",
    brand: "Bvlgari",
    volume: [100],
    tone: "Warm & Spicy",
    scentFamily: "Woody Oriental",
    perfumer: [],
    gender: "Men",
    perfumeType: "Eau de Parfum",
    season: "Autumn, Winter",
    longevity: "Long",
    sillage: "Strong",
    price: 110,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Bvlgari Orom",
    brand: "Bvlgari",
    volume: [100],
    tone: "Fresh & Citrus",
    scentFamily: "Aromatic Citrus",
    perfumer: [],
    gender: "Men",
    perfumeType: "Eau de Toilette",
    season: "Spring, Summer",
    longevity: "Moderate",
    sillage: "Moderate",
    price: 95,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Bentley Azure",
    brand: "Bentley",
    volume: [100],
    tone: "Fresh & Citrus",
    scentFamily: "Aromatic Aquatic",
    perfumer: [],
    gender: "Men",
    perfumeType: "Eau de Toilette",
    season: "Spring, Summer",
    longevity: "Moderate",
    sillage: "Moderate",
    price: 85,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Bentley Infinite",
    brand: "Bentley",
    volume: [100],
    tone: "Fresh & Woody",
    scentFamily: "Woody Aromatic",
    perfumer: [],
    gender: "Men",
    perfumeType: "Eau de Toilette",
    season: "Spring, Summer",
    longevity: "Moderate",
    sillage: "Moderate",
    price: 90,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Bentley Infinite Rush",
    brand: "Bentley",
    volume: [100],
    tone: "Fresh & Citrus",
    scentFamily: "Aromatic Aquatic",
    perfumer: [],
    gender: "Men",
    perfumeType: "Eau de Toilette",
    season: "Spring, Summer",
    longevity: "Moderate",
    sillage: "Moderate",
    price: 95,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Bentley Silverlake",
    brand: "Bentley",
    volume: [100],
    tone: "Warm & Spicy",
    scentFamily: "Woody Spicy",
    perfumer: [],
    gender: "Men",
    perfumeType: "Eau de Parfum",
    season: "Autumn, Winter",
    longevity: "Long",
    sillage: "Strong",
    price: 100,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Bentley Momentum",
    brand: "Bentley",
    volume: [100],
    tone: "Fresh & Woody",
    scentFamily: "Woody Aromatic",
    perfumer: [],
    gender: "Men",
    perfumeType: "Eau de Toilette",
    season: "Spring, Summer",
    longevity: "Moderate",
    sillage: "Moderate",
    price: 90,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Bentley Absolute",
    brand: "Bentley",
    volume: [100],
    tone: "Warm & Spicy",
    scentFamily: "Woody Oriental",
    perfumer: [],
    gender: "Men",
    perfumeType: "Eau de Parfum",
    season: "Autumn, Winter",
    longevity: "Long",
    sillage: "Strong",
    price: 105,
    available: true,
    discount: 0,
    image: [],
    description: "توضیحات عطر",
  },
  {
    name: "Bentley Momentum Intense",
    brand: "Bentley",
    volume: [100],
    tone: "Warm & Spicy",
    scentFamily: "Woody Spicy",
    perfumer: [],
    gender: "Men",
    perfumeType: "Eau de Toilette",
    season: "Autumn, Winter",
    longevity: "Long",
    sillage: "Moderate",
    price: 80,
    available: true,
    discount: 0,
    image: [],
    description: "",
  },
  {
    name: "Bentley For Men",
    brand: "Bentley",
    volume: [100],
    tone: "Warm & Spicy",
    scentFamily: "Woody Spicy",
    perfumer: [],
    gender: "Men",
    perfumeType: "Eau de Toilette",
    season: "Autumn, Winter",
    longevity: "Moderate",
    sillage: "Moderate",
    price: 70,
    available: true,
    discount: 0,
    image: [],
    description: "",
  },
  {
    name: "Bentley Intense",
    brand: "Bentley",
    volume: [100],
    tone: "Warm & Spicy",
    scentFamily: "Woody Spicy",
    perfumer: [],
    gender: "Men",
    perfumeType: "Eau de Toilette",
    season: "Autumn, Winter",
    longevity: "Long",
    sillage: "Moderate",
    price: 85,
    available: true,
    discount: 0,
    image: [],
    description: "",
  },
  {
    name: "Bijan for Women",
    brand: "Bijan",
    volume: [100],
    tone: "Floral & Sweet",
    scentFamily: "Floral",
    perfumer: [],
    gender: "Women",
    perfumeType: "Eau de Toilette",
    season: "Spring, Summer",
    longevity: "Moderate",
    sillage: "Moderate",
    price: 70,
    available: true,
    discount: 0,
    image: [],
    description: "",
  },
  {
    name: "Bijan VIP for Women",
    brand: "Bijan",
    volume: [100],
    tone: "Warm & Sweet",
    scentFamily: "Oriental Floral",
    perfumer: [],
    gender: "Women",
    perfumeType: "Eau de Parfum",
    season: "Autumn, Winter",
    longevity: "Long",
    sillage: "Moderate",
    price: 85,
    available: true,
    discount: 0,
    image: [],
    description: "",
  },
  {
    name: "Bijan for Men",
    brand: "Bijan",
    volume: [100],
    tone: "Warm & Spicy",
    scentFamily: "Woody Spicy",
    perfumer: [],
    gender: "Men",
    perfumeType: "Eau de Toilette",
    season: "Autumn, Winter",
    longevity: "Moderate",
    sillage: "Moderate",
    price: 75,
    available: true,
    discount: 0,
    image: [],
    description: "",
  },
  {
    name: "Bijan Nude Men",
    brand: "Bijan",
    volume: [100],
    tone: "Fresh & Aromatic",
    scentFamily: "Woody Aromatic",
    perfumer: [],
    gender: "Men",
    perfumeType: "Eau de Toilette",
    season: "Spring, Summer",
    longevity: "Moderate",
    sillage: "Moderate",
    price: 80,
    available: true,
    discount: 0,
    image: [],
    description: "",
  },
];
