export const perfumes = [
  {
    name: "fuckin fabulous",
    brand: "tomford",
    volume: 100,
    tone: "warm and sweet",
    scentFamily: "floral",
    perfumer: "tom ford",
    gender: "male",
    perfumeType: "eau de parfum",
    season: "all year",
    longevity: "long",
    sillage: "medium",
    id: 1,
    price: 100000,
    available: false,
    discount: 0,
  },
  {
    name: "fuckin fabulous",
    brand: "tomford",
    volume: 100,
    tone: "warm and sweet",
    scentFamily: "floral",
    perfumer: "tom ford",
    gender: "female",
    perfumeType: "eau de parfum",
    season: "all year",
    longevity: "long",
    sillage: "medium",
    id: 2,
    price: 100000,
    available: true,
    discount: 0,
  },
  {
    name: "fuckin fabulous",
    brand: "tomford",
    volume: 100,
    tone: "warm and sweet",
    scentFamily: "floral",
    perfumer: "tom ford",
    gender: "unisex",
    perfumeType: "eau de parfum",
    season: "all year",
    longevity: "long",
    sillage: "medium",
    id: 3,
    price: 100000,
    available: true,
    discount: 0,
  },
  {
    name: "fuckin fabulous",
    brand: "tomford",
    volume: 100,
    tone: "warm and sweet",
    scentFamily: "floral",
    perfumer: "tom ford",
    gender: "unisex",
    perfumeType: "eau de parfum",
    season: "all year",
    longevity: "long",
    sillage: "medium",
    id: 4,
    price: 100000,
    available: true,
    discount: 0,
  },
  {
    name: "fuckin fabulous",
    brand: "tomford",
    volume: 100,
    tone: "warm and sweet",
    scentFamily: "floral",
    perfumer: "tom ford",
    gender: "unisex",
    perfumeType: "eau de parfum",
    season: "all year",
    longevity: "long",
    sillage: "medium",
    id: 5,
    price: 100000,
    available: true,
    discount: 0,
  },
  {
    name: "fuckin fabulous",
    brand: "tomford",
    volume: 100,
    tone: "warm and sweet",
    scentFamily: "floral",
    perfumer: "tom ford",
    gender: "unisex",
    perfumeType: "eau de parfum",
    season: "all year",
    longevity: "long",
    sillage: "medium",
    id: 44,
    price: 100000,
    available: true,
    discount: 0,
  },
  {
    name: "fuckin fabulous",
    brand: "tomford",
    volume: 100,
    tone: "warm and sweet",
    scentFamily: "floral",
    perfumer: "tom ford",
    gender: "unisex",
    perfumeType: "eau de parfum",
    season: "all year",
    longevity: "long",
    sillage: "medium",
    id: 6,
    price: 100000,
    available: true,
    discount: 0,
  },
  {
    name: "fuckin fabulous",
    brand: "tomford",
    volume: 100,
    tone: "warm and sweet",
    scentFamily: "floral",
    perfumer: "tom ford",
    gender: "unisex",
    perfumeType: "eau de parfum",
    season: "all year",
    longevity: "long",
    sillage: "medium",
    id: 7,
    price: 100000,
    available: true,
    discount: 0,
  },
  {
    name: "fuckin fabulous",
    brand: "tomford",
    volume: 100,
    tone: "warm and sweet",
    scentFamily: "floral",
    perfumer: "tom ford",
    gender: "unisex",
    perfumeType: "eau de parfum",
    season: "all year",
    longevity: "long",
    sillage: "medium",
    id: 8,
    price: 100000,
    available: true,
    discount: 0,
  },
  {
    name: "fuckin fabulous",
    brand: "tomford",
    volume: 100,
    tone: "warm and sweet",
    scentFamily: "floral",
    perfumer: "tom ford",
    gender: "unisex",
    perfumeType: "eau de parfum",
    season: "all year",
    longevity: "long",
    sillage: "medium",
    id: 9,
    price: 100000,
    available: true,
    discount: 0,
  },
  {
    name: "fuckin fabulous",
    brand: "tomford",
    volume: 100,
    tone: "warm and sweet",
    scentFamily: "floral",
    perfumer: "tom ford",
    gender: "unisex",
    perfumeType: "eau de parfum",
    season: "all year",
    longevity: "long",
    sillage: "medium",
    id: 14,
    price: 100000,
    available: true,
    discount: 0,
  },
  {
    name: "fuckin fabulous",
    brand: "tomford",
    volume: 100,
    tone: "warm and sweet",
    scentFamily: "floral",
    perfumer: "tom ford",
    gender: "unisex",
    perfumeType: "eau de parfum",
    season: "all year",
    longevity: "long",
    sillage: "medium",
    id: 10,
    price: 100000,
    available: true,
    discount: 0,
  },
];
