export const sampleOrders = [
  {
    id: 1,
    orderNumber: "ORD-2024-001",
    date: "2024-01-15",
    status: "delivered" as const,
    totalAmount: 8500000,
    items: [
      {
        id: 1,
        name: "Acqua di Gio",
        brand: "Giorgio Armani",
        price: 2500000,
        volume: 100,
        perfumeType: "Eau de Toilette",
        gender: "male",
        quantity: 2,
      },
      {
        id: 2,
        name: "Chanel N°5",
        brand: "Chanel",
        price: 3200000,
        volume: 50,
        perfumeType: "Eau de Parfum",
        gender: "female",
        quantity: 1,
      },
    ],
  },
  {
    id: 2,
    orderNumber: "ORD-2024-002",
    date: "2024-01-20",
    status: "processing" as const,
    totalAmount: 5600000,
    items: [
      {
        id: 3,
        name: "Bleu de Chanel",
        brand: "Chanel",
        price: 2800000,
        volume: 100,
        perfumeType: "Eau de Parfum",
        gender: "male",
        quantity: 2,
      },
    ],
  },
  {
    id: 3,
    orderNumber: "ORD-2024-003",
    date: "2024-01-25",
    status: "shipped" as const,
    totalAmount: 4200000,
    items: [
      {
        id: 4,
        name: "La Vie Est Belle",
        brand: "Lancôme",
        price: 2100000,
        volume: 50,
        perfumeType: "Eau de Parfum",
        gender: "female",
        quantity: 2,
      },
    ],
  },
  {
    id: 4,
    orderNumber: "ORD-2024-004",
    date: "2024-01-30",
    status: "pending" as const,
    totalAmount: 1800000,
    items: [
      {
        id: 5,
        name: "Sauvage",
        brand: "Dior",
        price: 1800000,
        volume: 100,
        perfumeType: "Eau de Toilette",
        gender: "male",
        quantity: 1,
      },
    ],
  },
];
